CREATE TABLE IF NOT EXISTS `#__akeebasubs_relations` (
  `akeebasubs_relation_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `source_level_id` BIGINT(20) NOT NULL DEFAULT 0,
  `target_level_id` BIGINT(20) NOT NULL DEFAULT 0,
  `mode` ENUM('rules','fixed','flexi') NOT NULL DEFAULT 'flexi',
  `type` ENUM('percent','value') NOT NULL DEFAULT 'percent',
  `amount` FLOAT NOT NULL DEFAULT 0.0,
  `low_threshold` INTEGER NOT NULL DEFAULT 0,
  `low_amount` FLOAT NOT NULL DEFAULT 0.0,
  `high_threshold` INTEGER NOT NULL DEFAULT 0,
  `high_amount` FLOAT NOT NULL DEFAULT 0.0,
  `flex_amount` FLOAT NOT NULL DEFAULT 0.0,
  `flex_period` INTEGER NOT NULL DEFAULT 0,
  `flex_uom` ENUM('d','w','m','y') NOT NULL DEFAULT 'd',
  `flex_timecalculation` ENUM('current','future') NOT NULL DEFAULT 'current',
  `time_rounding` ENUM('floor','ceil','round') NOT NULL DEFAULT 'round',
  `expiration` ENUM('replace','after','overlap') NOT NULL DEFAULT 'replace',
  `combine` tinyint(3) NOT NULL DEFAULT '0',
  `enabled` tinyint(3) NOT NULL DEFAULT '0',
  `ordering` bigint(20) unsigned NOT NULL,
  `created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` int(11) NOT NULL DEFAULT '0',
  `modified_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` int(11) NOT NULL DEFAULT '0',
  `locked_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `locked_by` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`akeebasubs_relation_id`),
  UNIQUE KEY `akeebasubs_relation_unique` (`source_level_id`,`target_level_id`),
  KEY `akeebasubs_relations_target` (`target_level_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;